# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='documents/%Y/%m/%d')),
                ('thumbnail', models.FileField(blank=True, max_length=500, null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
