# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160229_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
